### ISSUE TITLE
File Write Errors on Windows Systems

### ISSUE THREAD

**Issue by SatoTake2019** [fabiocaccamo/django-maintenance-mode#180] opened 2024-02-12 02:09 UTC
Dear django-maintenance-mode developers

Thank you for the excellent package.

I am encountering an issue with file write errors on Windows systems while using your package. Here is my setup:

**Environment**

- OS: Windows 11 Home 23H2
- pyenv-win 3.1.1
- Python 3.10.11
- Django 3.2
- django-maintenance-mode 0.21.1
- python-fsutil 0.13.1

**Problem**

When I start `runserver `and access "localhost:8000/", it tries to read config/settings/maintenance_mode_state.txt, but since this file does not exist, it tries to create the file (the creation actually fails). A maintenance_mode_state.txt file expected to be created, but this file does not exist. This result is as follow:
```
2024-02-12 08:57:07,188 [ERROR] D:\PyCharmProjects\shiftpat-second\venv\lib\site-packages\django\utils\log.py:224 Internal Server Error: /ja/
Traceback (most recent call last):
  File "D:\PyCharmProjects\shiftpat-second\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\PyCharmProjects\shiftpat-second\venv\lib\site-packages\maintenance_mode\middleware.py", line 9, in __call__
    response = self.process_request(request)
  File "D:\PyCharmProjects\shiftpat-second\venv\lib\site-packages\maintenance_mode\middleware.py", line 15, in process_request
    if need_maintenance_response(request):
  File "D:\PyCharmProjects\shiftpat-second\venv\lib\site-packages\maintenance_mode\http.py", line 232, in need_maintenance_response
    value = get_maintenance_mode()
  File "D:\PyCharmProjects\shiftpat-second\venv\lib\site-packages\maintenance_mode\core.py", line 40, in get_maintenance_mode
    return backend.get_value()
  File "D:\PyCharmProjects\shiftpat-second\venv\lib\site-packages\maintenance_mode\backends.py", line 90, in get_value
    value = read_file(self._get_filepath(), "0")
  File "D:\PyCharmProjects\shiftpat-second\venv\lib\site-packages\maintenance_mode\io.py", line 12, in read_file
    return fsutil.read_file(file_path) or default_content
  File "D:\PyCharmProjects\shiftpat-second\venv\lib\site-packages\fsutil\__init__.py", line 997, in read_file
    assert_file(path)
  File "D:\PyCharmProjects\shiftpat-second\venv\lib\site-packages\fsutil\__init__.py", line 168, in assert_file
    raise OSError(f"Invalid file path: {path}")
OSError: Invalid file path: D:\PyCharmProjects\shiftpat-second\myapps\config\settings\maintenance_mode_state.txt
2024-02-12 08:57:07,191 [ERROR] D:\PyCharmProjects\shiftpat-second\venv\lib\site-packages\django\core\servers\basehttp.py:161 "GET /ja/ HTTP/1.1" 500 125619
```
This is the same whether it is the default behavior that does not specify MAINTENANCE_MODE_STATE_FILE_PATH or if it is specified in config.settings.base.py as shown below. 
As mentioned above, the file is not created by write_file_func in fsutil.write_file, so the above error seems to occur.
`MAINTENANCE_MODE_STATE_FILE_PATH = os.path.join(BASE_DIR, 'config/settings/maintenance_mode_state.txt'.replace('/', os.sep))`

Also, if I create maintenance_mode_state.txt in advance as shown below, the file will exist and the application page will be displayed without error when I access "localhost:8000/".
```
$ touch myapps/config/settings/maintenance_mode_state.txt
$ echo 0 > myapps/config/settings/maintenance_mode_state.txt
```
In that state, I run the next command:
`$ python manage.py maintenance_mode on`
When it performs write_file() on line 96 of backends.py, the maintenance_mode_state.txt created above was deleted in somewhere after write_file_func on line 1401 of fsutil.__init__
However, this maintenance_mode on command itself completes normally without any errors.
Then, runserver is still running, so if you try to access some page (for example, "localhost:8000/") again, it will go through the same call stack for the same reason as I wrote at the beginning, and I receive the same error.

The above problem did not occur when running in an Ubuntu environment on WSL.

I think it's a problem with python-fsutil, not django-maintenance-mode, so should I write about it in that issue?

Thank you for your time and assistance.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-maintenance-mode/issues/180">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-maintenance-mode/issues/180/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-maintenance-mode/issues/180/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment] 2024-02-12 07:21
@SatoTake2019 thanks for reporting this and for the debugging of the problem. Yes, that's an `fsutil` issue, probably related to permissions on Windows, could you move this issue ti the `fsutil` repo please?

**Comment by SatoTake2019** [comment] 2024-02-12 12:14
I reported [python-fsutil#109](https://github.com/fabiocaccamo/python-fsutil/issues/109).
I don't know the operation of "moving an issue". Sorry if I'm wrong.

**Comment by fabiocaccamo** [comment] 2024-02-12 13:38
@SatoTake2019 you did exactly what I meant, thanks!

**Comment by SatoTake2019** [comment] 2024-02-12 15:18
@fabiocaccamo You are welcome.

**Comment by fabiocaccamo** [comment] 2024-02-15 17:18
@SatoTake2019 ok, since I can't reproduce it, I close the issue for now, when you will be able to provide more informations on https://github.com/fabiocaccamo/python-fsutil/issues/109 I will be glad to reopen both issues.

**Closed by fabiocaccamo** 2024-02-15 17:18 UTC
Labels: bug

**Comment by fabiocaccamo** [comment] 2024-02-15 17:46
@SatoTake2019 could you try to install `django-maintenance-mode` from main branch and let me know if the [this commit](9a71768d8ca6f2b8a7ffb639737a75bcf79a7998) fixes the issue?
